# Package name, module, and list of source files

NAME=Utils
CCSRCS=MathUtil.cpp \
	   TypeUtil.cpp \
	   StringUtil.cpp \
	   FileSystemUtil.cpp \
	   FileUtil.cpp \
	   ColorUtil.cpp \
	   GLUTUtil.cpp


#
# Set up compiler options, USER_CFLAGS
#

# R3 library makefile
include ../../makefiles/Makefile.pkgs
